# ======================================================
# Recommended Configuration
# ======================================================

directory: /home/justin/media/Music
library: /home/justin/.config/beets/library.db
pluginpath: /home/justin/.local/share/beets/plugins

# --- Import Settings ---
import:
  copy: yes
  move: no
  delete: no
  quiet: no
  resume: yes
  timid: no
  autotag: yes
  log: /home/justin/.config/beets/beets_import.log
  duplicate_action: ask

# --- Path Formats ---
paths:
  default: $albumartist/$album%aunique{}/$track $title
  comp: Compilations/$album%aunique{}/$track $title
  singleton: Singletons/$artist/$title

# --- Enabled Plugins ---
plugins: duplicates scrub fetchart lastgenre embedart info edit export replaygain chroma mbsync

# --- Plugin Configuration ---

musicbrainz:
  extra_tags: [
      original_date, 
      original_year, 
      recording_year, 
      recording_month, 
      recording_day,
      recording_disambig
  ]
  host: musicbrainz.org
  ratelimit: 100
  releasegroup_types:
    - live
    - compilation
    - soundtrack
    - remix

oldestdate:
  auto: yes
  ignore_track_id: yes
  filter_on_import: yes
  prompt_missing_work_id: yes
  force: no
  overwrite_date: yes # This will correctly set year, month, day based on the oldest date found.
  filter_recordings: yes
  approach: 'releases'

# The item_fields section for 'year' has been removed to avoid conflict with 'oldestdate'.

# ... (rest of your plugin configs like duplicates, scrub, etc. are fine) ...
duplicates:
  delete: no
  strict: yes
  checksum: md5sum $path
  tiebreak:
    albumtype: album soundtrack
    format: FLAC MP3 AAC Ogg Vorbis
    bitrate: desc

scrub:
  auto: yes

fetchart:
  auto: yes
  minwidth: 300
  maxwidth: 1000
  cautious: no
  store_source: yes

embedart:
  auto: yes
  maxwidth: 1000

lastgenre:
  whitelist: yes
  count: 3
  source: album
  min_weight: 10
  fallback: Unknown
  force: no
  separator: ', '
  prefer_specific: no
  canonical: no

replaygain:
  backend: ffmpeg
  auto: no
  overwrite: yes
  threads: 1
  targetlevel: 89

# --- Matching Thresholds & Preferences ---
match:
  strong_rec_thresh: 0.04
  medium_rec_thresh: 0.25
  weak_rec_thresh: 0.50
  use_original: yes
  ignored: [asin, amazon_id, acoustid_fingerprint, acoustid_id, script, language]
  preferred:
    media: [CD, Digital Media]
    original_year: yes
    countries: ['US', 'GB', 'XW', 'CA', 'AU', 'DE', 'FR', 'JP']
    formats: ['FLAC', 'ALAC', 'AIFF', 'WAV', 'MP3', 'AAC', 'OGG']
  ignored:
    media: [Vinyl, Cassette, Other]

# In your config.yaml

#asciify_paths: yes

#replace:
#    '[\\/]': _  # Replace slashes with underscores in tags.
#    '^\.': _    # Replace leading dots with underscores.
#    '[\x00-\x1f]': _ # Replace non-printable characters with underscores.
#    '[<>:"\?\*\|]': _ # Replace characters illegal in Windows paths.
#    '’': "'"    # Replace right single quote with a plain apostrophe.
#    '‘': "'"    # Replace left single quote with a plain apostrophe.
#    '”': '"'    # Replace right double quote with a plain double quote.
#    '“': '"'    # Replace left double quote with a plain double quote.
#    '…': ...    # Replace ellipsis with three periods.