# Alacritty Config for Dark, Eye-Friendly Geek Aesthetic
[window]
opacity = 0.9
padding.x = 10
padding.y = 10
decorations = "Full"
dynamic_title = true
dimensions.columns = 100
dimensions.lines = 30

[font]
size = 10

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.offset]
x = 0
y = 1

[font.glyph_offset]
x = 0
y = 0

[colors]
# Dark, cyberpunk-inspired theme
[colors.primary]
background = "#1a1b26" # Deep navy-gray
foreground = "#c0caf5" # Soft white

[colors.cursor]
text = "#1a1b26"
cursor = "#7aa2f7" # Neon blue

[colors.normal]
black = "#32344a"
red = "#f7768e"
green = "#9ece6a" # Geeky neon green
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#ad8ee6" # Subtle neon purple
cyan = "#449dab"
white = "#787c99"

[colors.bright]
black = "#444b6a"
red = "#ff7a93"
green = "#b9f27c"
yellow = "#ff9e64"
blue = "#7da6ff"
magenta = "#bb9af7"
cyan = "#0db9d7"
white = "#acb0d0"

[cursor]
style.shape = "Beam"
style.blinking = "On"
blink_interval = 500
unfocused_hollow = true

[scrolling]
history = 10000
multiplier = 3

[[key_bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[key_bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[key_bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[key_bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[key_bindings]]
key = "T"
mods = "Control|Shift"
action = "SpawnNewInstance"


